import { randomUUID } from "node:crypto";
import { SignJWT } from "jose";
import { afterAll, beforeAll, describe, expect, it } from "vitest";

import { buildApp } from "../src/app.js";
import { getPool } from "../src/db/pool.js";

describe("explicit author workspace scope", () => {
  const suffix = randomUUID().slice(0, 8); const tenantId = "tnt_default"; const userA = `usr_scope_a_${suffix}`; const userB = `usr_scope_b_${suffix}`; const authorA = `author-a-${suffix}`; const authorB = `author-b-${suffix}`; const appA = `aap_a_${suffix}`; const appB = `aap_b_${suffix}`;
  beforeAll(async () => { process.env["DATABASE_URL"] ??= "postgres://hc_user:hc_password@localhost:5432/hc_core"; process.env["JWT_SECRET"] = "supersecretkeysupersecret"; process.env["JWT_ISSUER"] = "hekatoncheiros-core"; process.env["JWT_AUDIENCE_USER"] = "hc-user"; process.env["DEFAULT_TENANT_ID"] = tenantId; const pool = getPool(); await pool.query("insert into core.users(id,email,password_hash,status) values($1,$2,'test','active'),($3,$4,'test','active')", [userA, `${userA}@example.test`, userB, `${userB}@example.test`]); await pool.query(`insert into core.author_profiles(author_id,display_name,contact_email,operating_mode,owner_tenant_id,registry_status) values($1,'Author A',$2,'talpaversum_hosted',$3,'active'),($4,'Author B',$5,'talpaversum_hosted',$3,'active')`, [authorA, `${userA}@example.test`, tenantId, authorB, `${userB}@example.test`]); const permissions = JSON.stringify(["author.apps.read", "author.apps.submit", "author.audit.read"]); await pool.query("insert into core.author_memberships(author_id,user_id,role,permissions_json) values($1,$2,'developer',$3::jsonb),($4,$5,'developer',$3::jsonb)", [authorA, userA, permissions, authorB, userB]); await pool.query(`insert into core.author_apps(author_app_id,author_id,display_name,status,runtime_management,licensing_management,created_by) values($1,$2,'App A','ready_for_review','talpaversum_managed','talpaversum_hosted',$3),($4,$5,'App B','ready_for_review','talpaversum_managed','talpaversum_hosted',$6)`, [appA, authorA, userA, appB, authorB, userB]); });
  afterAll(async () => { const pool = getPool(); await pool.query("delete from core.author_profiles where author_id=any($1::text[])", [[authorA, authorB]]); await pool.query("delete from core.users where id=any($1::text[])", [[userA, userB]]); });
  it("never returns or mutates objects from another author", async () => { const app = await buildApp(); const token = await new SignJWT({ tenant_id: tenantId }).setProtectedHeader({ alg: "HS256" }).setSubject(userA).setIssuer("hekatoncheiros-core").setAudience("hc-user").setIssuedAt().setExpirationTime("5m").sign(new TextEncoder().encode(process.env["JWT_SECRET"])); const headers = { authorization: `Bearer ${token}` }; const own = await app.inject({ method: "GET", url: `/api/v1/author-portal/authors/${authorA}/apps`, headers }); expect(own.statusCode).toBe(200); expect((own.json() as { items: Array<{ author_id: string }> }).items).toEqual([expect.objectContaining({ author_id: authorA })]); const foreign = await app.inject({ method: "GET", url: `/api/v1/author-portal/authors/${authorB}/apps`, headers }); expect(foreign.statusCode).toBe(403); expect(foreign.json()).toMatchObject({ code: "author_scope_forbidden" }); const mutation = await app.inject({ method: "POST", url: `/api/v1/author-portal/authors/${authorA}/apps/${appB}/action`, headers, payload: { action: "submit" } }); expect(mutation.statusCode).toBe(404); await app.close(); });
});
