apiVersion: v1
kind: ConfigMap
metadata:
  name: hekatoncheiros-config
data:
  NODE_ENV: production
  PORT: "3000"
  CORE_DATA_DIR: /var/lib/hekatoncheiros/core-data
  TENANCY_MODE: row_level
  JWT_ISSUER: hekatoncheiros-core
  JWT_AUDIENCE_USER: hc-user
  JWT_AUDIENCE_APP: hc-app
  INSTALLER_TOKEN_ISSUER: hekatoncheiros-core-installer
  DEFAULT_TENANT_ID: tnt_default
  APP_RUNTIME_DOCKER_ENABLED: "false"
  APP_CATALOG_AUTO_REFRESH_ENABLED: "false"
  APP_CATALOG_AUTO_REFRESH_INTERVAL_SECONDS: "300"

