apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hekatoncheiros
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [hc.example.com]
      secretName: hekatoncheiros-tls
  rules:
    - host: hc.example.com
      http:
        paths:
          - path: /api/v1
            pathType: Prefix
            backend:
              service:
                name: core
                port:
                  name: http
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: core
                port:
                  name: http
          - path: /.well-known/hc/app-catalog.json
            pathType: Exact
            backend:
              service:
                name: core
                port:
                  name: http
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  name: http

